[project]
name = "python-projects"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tango", email = "csqingyang@foxmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.1",
    "mypy>=2.3.0",
    "pandas>=3.0.3",
    "pytest>=9.1.1",
    "pyyaml>=6.0.3",
    "torch>=2.13.0",
]

[build-system]
requires = ["uv_build>=0.11.2,<0.12.0"]
build-backend = "uv_build"
